"""initial

Revision ID: 11579f5bec62
Revises: 
Create Date: 2026-05-19 13:41:41.279549

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '11579f5bec62'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('brand',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=40), nullable=False),
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('logo_path', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('faq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('signup', 'vehicle', 'subscription', 'insurance', 'inspection', 'return', 'etc', name='faq_category'), nullable=False),
    sa.Column('question', sa.String(length=300), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('site_setting',
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('kakao_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=60), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('is_admin', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('marketing_opt_in', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_kakao_id'), ['kakao_id'], unique=True)

    op.create_table('vehicle',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand_id', sa.Integer(), nullable=False),
    sa.Column('model', sa.String(length=80), nullable=False),
    sa.Column('trim', sa.String(length=80), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('color', sa.String(length=40), nullable=True),
    sa.Column('fuel', sa.Enum('gasoline', 'diesel', 'hybrid', 'ev', 'lpg', name='vehicle_fuel'), nullable=True),
    sa.Column('transmission', sa.Enum('auto', 'manual', name='vehicle_transmission'), nullable=True),
    sa.Column('mileage_km', sa.Integer(), nullable=True),
    sa.Column('plate', sa.String(length=20), nullable=True),
    sa.Column('new_price_man', sa.Integer(), nullable=True),
    sa.Column('headline', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('options_json', sa.JSON(), nullable=True),
    sa.Column('product_type', sa.Enum('subscription', 'rent', 'super', name='vehicle_product_type'), nullable=False),
    sa.Column('price_min_man', sa.Integer(), nullable=True),
    sa.Column('price_max_man', sa.Integer(), nullable=True),
    sa.Column('visibility', sa.Enum('public', 'hidden', 'soldout', name='vehicle_visibility'), nullable=False),
    sa.Column('placement', sa.Enum('collection', 'none', name='vehicle_placement'), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('is_fast', sa.Boolean(), nullable=False),
    sa.Column('is_deal', sa.Boolean(), nullable=False),
    sa.Column('eta_label', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['brand_id'], ['brand.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_brand_id'), ['brand_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_placement'), ['placement'], unique=False)
        batch_op.create_index(batch_op.f('ix_vehicle_visibility'), ['visibility'], unique=False)

    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'vehicle_id', name='uq_user_vehicle_fav')
    )
    op.create_table('inquiry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('vehicle_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=40), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('upcoming_slot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('group', sa.Enum('a', 'b', name='upcoming_group'), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vehicle_id')
    )
    with op.batch_alter_table('upcoming_slot', schema=None) as batch_op:
        batch_op.create_index('ix_upcoming_group_position', ['group', 'position'], unique=False)

    op.create_table('vehicle_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.String(length=255), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicle.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vehicle_image', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vehicle_image_vehicle_id'), ['vehicle_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle_image', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_image_vehicle_id'))

    op.drop_table('vehicle_image')
    with op.batch_alter_table('upcoming_slot', schema=None) as batch_op:
        batch_op.drop_index('ix_upcoming_group_position')

    op.drop_table('upcoming_slot')
    op.drop_table('inquiry')
    op.drop_table('favorite')
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vehicle_visibility'))
        batch_op.drop_index(batch_op.f('ix_vehicle_placement'))
        batch_op.drop_index(batch_op.f('ix_vehicle_brand_id'))

    op.drop_table('vehicle')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_kakao_id'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('site_setting')
    op.drop_table('notice')
    op.drop_table('faq')
    op.drop_table('brand')
    # ### end Alembic commands ###
