"""add banner

Revision ID: 7990d022da8d
Revises: 11579f5bec62
Create Date: 2026-05-19 17:13:47.941271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7990d022da8d'
down_revision = '11579f5bec62'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('banner',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('eyebrow', sa.String(length=60), nullable=True),
    sa.Column('title', sa.String(length=120), nullable=False),
    sa.Column('subtitle', sa.String(length=200), nullable=True),
    sa.Column('link_url', sa.String(length=255), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('banner')
    # ### end Alembic commands ###
